-d C:\Softs\Gowin\Projects\LCD_fpga_project\impl\gwsynthesis\LCD_fpga_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Softs\Gowin\Projects\LCD_fpga_project\src\LCD_fpga_project.cst
-cfg C:\Softs\Gowin\Projects\LCD_fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
